---
title: "Scatterplot"
author: "Ryan S"
date: "2022-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loads the necessary packages and variables for the project. Also saves the alzheimer dataset to a simpler name 'alz'
```{r}
library(ggplot2)
library(tidyverse)
library(janitor)
library(readr)
alz <- readr::read_csv("alzheimer_data.csv")
attach(alz)
```

## Creates a bar graph which compares diagnosis with gender (male and female). 
```{r}
ggplot(alz, aes(x=diagnosis, fill = factor(female)))+
  geom_bar(size = 2,
             alpha = 2)+
  scale_color_brewer(palette = "Pastel1",
                     type = qual)+ #looks at different colors
  theme_bw()
```

## Creates a scatterplot which compares left hippocampus volume to how old the patient is, and how the older a subject gets,
## the smaller the left hippocampus gets.
```{r}
fem <- factor(female, labels=c('male', 'female'))
ggplot(alz, aes(x=age, y=lhippo, color = fem))+
  geom_point(size = 2, shape = 16,
             alpha = 10)+
  geom_smooth(method=lm)+
  scale_color_brewer(palette = "Accent",
                     type = qual)+
  theme_bw()
```

```{r}
chisq.test(fem, y = diagnosis)
```